[build]
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"